### ISSUE TITLE
Bug running hnsw on sparse matrices

### ISSUE THREAD

**Issue by davisidarta** [nmslib/nmslib#444]
Hello, has any progress been done in running hnsw on sparse matrices? I'm having an error working on csr sparse matrices with the 'cosinesimil' space. In fact, this happens with any method I try. A similar issue has been reported in #336. Here's my code - I'm building a sklearn wrapper for nmslib so as to integrate it with a dimensional reduction method I'm developing.

```
####
#create a sklearn wrapper for nmslib
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from scipy.sparse import csr_matrix, find, issparse
from scipy.sparse.linalg import eigs
import hnswlib

import time
import sys

try:
    import nmslib
except ImportError:
    print("The package 'nmslib' is required to run accelerated dbMAP")
    sys.exit()

import numpy as np
from scipy.sparse import csr_matrix

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.neighbors import KNeighborsTransformer
from sklearn.utils._testing import assert_array_almost_equal

print(__doc__)


class NMSlibTransformer(TransformerMixin, BaseEstimator):
    """Wrapper for using nmslib as sklearn's KNeighborsTransformer"""

    def __init__(self, n_neighbors=5, metric='cosinesimil', method='hnsw',
                 n_jobs=-1, data_type=nmslib.DataType.SPARSE_VECTOR):
        self.n_neighbors = n_neighbors
        self.method = method
        self.metric = metric
        self.n_jobs = n_jobs
        self.data_type = data_type
    def fit(self, data):
        self.n_samples_fit_ = data.shape[0]

        # see more metric in the manual
        # https://github.com/nmslib/nmslib/tree/master/manual
        space = {
            'sqeuclidean': 'l2',
            'euclidean': 'l2',
            'cosinesimil': 'cosinesimil',
            'cosinesimil_sparse' : 'cosinesimil_sparse',
            'l1': 'l1',
            'l2': 'l2',
            'bit_hamming' : 'bit_hamming',
            'bit_jaccard' : 'bit_jaccard',
            'jaccard_sparse' : 'jaccard_sparse',
        }[self.metric]
        self.nmslib_ = nmslib.init(method=self.method,
                                   space=space,
                                   data_type=nmslib.DataType.SPARSE_VECTOR,
                                   dtype=nmslib.DistType.FLOAT)
        self.nmslib_.addDataPointBatch(data)
        self.nmslib_.createIndex()
        return self

    def transform(self, data):
        n_samples_transform = data.shape[0]

        # For compatibility reasons, as each sample is considered as its own
        # neighbor, one extra neighbor will be computed.
        n_neighbors = self.n_neighbors + 1

        results = self.nmslib_.knnQueryBatch(data, k=n_neighbors,
                                             num_threads=self.n_jobs)
        indices, distances = zip(*results)
        indices, distances = np.vstack(indices), np.vstack(distances)

        if self.metric == 'sqeuclidean':
            distances **= 2

        indptr = np.arange(0, n_samples_transform * n_neighbors + 1,
                           n_neighbors)
        kneighbors_graph = csr_matrix((distances.ravel(), indices.ravel(),
                                       indptr), shape=(n_samples_transform,
                                                       self.n_samples_fit_))

        return kneighbors_graph

    def test_transformers(self, data):
        """Test that NMSlibTransformer and KNeighborsTransformer give same results
        """
        X = np.random.RandomState(42).randn(10, 2)

        knn = KNeighborsTransformer()
        Xt0 = knn.fit_transform(data)

        nms = NMSlibTransformer()
        Xt1 = nms.fit_transform(data)

        assert_array_almost_equal(Xt0.toarray(), Xt1.toarray(), decimal=5)

#####
#Run example

data = csr_matrix((3, 3), dtype=np.float64)
data[0, 0] = 1
data[1, 0] = 2

anbrs = NMSlibTransformer(n_neighbors=1, metric='cosinesimil_sparse', method='hnsw', n_jobs=1)
anbrs = anbrs.fit(data)
```

This code invariably returns 
```
>>> anbrs = anbrs.fit(data)
Check failed: obj1->datalength() > 0
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 2, in <module>
  File "<input>", line 58, in fit
RuntimeError: Check failed: it's either a bug or inconsistent data!
```
 or
```
Check failed: obj1->datalength() == obj2->datalength()  #MULTIPLE and MULTIPLE times
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 3, in <module>
  File "<input>", line 57, in fit
RuntimeError: Check failed: it's either a bug or inconsistent data!
```

I was quite excited with accelerating my dimensionality reduction approach with nmslib for kNN computation, but this is disappointing because a series of data of interest is sparse, and converting them to dense formats and computing hnsw on those is more expensive than running sklearn on csr matrices.

This issue was first referred at #336, but there is no further information on whether this is a bug and if it got solved. Any hints?

Thank you for your help!

**Comment by searchivarius** [comment]
Hi @davisidarta it's an important bug to resolve. However, it's quite unusual to have fully empty vectors so it wasn't factored in before. As a workaround, you can replace an empty vector with a vector that has, e.g., zero coordinate with zero value.

**Comment by searchivarius** [comment]
Also @davisidarta is it the same bug or think something different happens?

**Comment by davisidarta** [comment]
Hi @searchivarius 

For now, I've managed to get everything up and running using only the 'cosinesimil_sparse_fast' metric, which absolutely works for what I need. I think the bug correction can be postponed for the time being.

The full code for wrapping nmslib on sklearn is now posted  [here](https://github.com/davisidarta/dbMAP/diffusion.py ), though I'll still work on some of it.

Thank you developers for such a wonderful library! 

Best,
Davi


Thank

**Comment by searchivarius** [comment]
Hi @davisidarta the bug doesn't manifest in the latest release and #336 should be fixed by now. So I am closing this issue. Feel free to ping me if there's any problem (or things didn't work with the latest nmslib). Thank you!
