### ISSUE TITLE
Segfault while loading index

### ISSUE THREAD

**Issue by sh1ng** [nmslib/nmslib#452]
Can it be because the index is empty?

```
nmslib.init(method='hnsw', space='cosinesimil')
index.createIndex({'post': 2}, print_progress=True)
index.saveIndex(cache, True)
index.loadIndex(cache, True)
```

```
#0  0x00007fa656ffb439 in similarity::Hnsw<float>::LoadRegularIndexBin (
    this=this@entry=0x13d3cb60, input=...)
    at ./similarity_search/src/method/hnsw.cc:943
943	./similarity_search/src/method/hnsw.cc: No such file or directory.
[Current thread is 1 (Thread 0x7fa6c0bdf740 (LWP 31801))]
(gdb) bt
#0  0x00007fa656ffb439 in similarity::Hnsw<float>::LoadRegularIndexBin (
    this=this@entry=0x13d3cb60, input=...)
    at ./similarity_search/src/method/hnsw.cc:943
#1  0x00007fa657001b89 in similarity::Hnsw<float>::LoadIndex (this=0x13d3cb60, 
    location="./tmp/_11_men_True")
    at ./similarity_search/src/method/hnsw.cc:986
#2  0x00007fa656f2c6e7 in similarity::IndexWrapper<float>::loadIndex (
    this=0x42e5f10, filename="./tmp/_11_men_True", load_data=<optimised out>)
    at nmslib.cc:108
#3  0x00007fa656f24867 in pybind11::cpp_function::cpp_function<void, similarity::IndexWrapper<float>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, char [169]>(void (similarity::IndexWrapper<float>::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg_v const&, char const (&) [169])::{lambda(similarity::IndexWrapper<float>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)#1}::operator()(similarity::IndexWrapper<float>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const (
    args#1=<optimised out>, args#0=..., c=<optimised out>, 
    __closure=<optimised out>)

```

[_11_men_True.zip](https://github.com/nmslib/nmslib/files/5058362/_11_men_True.zip)

**Comment by searchivarius** [comment]
Yeah, this is likely the case. I guess nobody tests empty indices :-)
